name: Build app

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_exe:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    name: Build app on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r pyproject.toml
          if [[ ${{ matrix.os }} == windows-* ]]; then          
            .venv\\Scripts\\activate.bat
            uv pip install -r pyproject.toml
            uv pip install eudplib
          else
            source .venv/bin/activate
            uv pip install eudplib-0.80.0-cp310-abi3-macosx_11_0_arm64.whl
          fi

      - name: Freeze app
        run: |
          if [[ ${{ matrix.os }} == macos-* ]]; then
            python setup.py bdist_mac
          elif [[ ${{ matrix.os }} == windows-* ]]; then
            python setup.py bdist_msi
          else
            # python setup.py bdist_appimage
            python setup.py build
          fi

      - name: Upload executable
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: build/**
          if-no-files-found: ignore
